name: solar_pro
description: SolarPro - Solar Installation & Sales Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.7

  # Network
  dio: ^5.4.3
  retrofit: ^4.1.0

  # Local Storage
  shared_preferences: ^2.2.3

  # UI / Animations
  animate_do: ^3.3.4
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Icons & Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8


  # Location (commented out until GPS screen is built - causes Windows build issue with spaces in path)
  # geolocator: ^12.0.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pin_code_fields: ^8.0.1
  fl_chart: ^0.68.0
  timeline_tile: ^2.0.0
  dotted_border: ^2.1.0
  badges: ^3.1.2
  country_code_picker: ^3.0.0
  phosphor_flutter: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

dependency_overrides:
  path_provider_foundation: 2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

