"""Pydantic schemas package."""
from app.schemas.auth import (
    FcmTokenUpdate,
    LogoutRequest,
    OtpRequest,
    OtpRequestResponse,
    OtpVerify,
    RefreshTokenRequest,
    TokenResponse,
    UserMeResponse,
)
from app.schemas.client import (
    ClientHomeResponse,
    ResponsibleContact,
    TimelineStageItem,
)
from app.schemas.common import (
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.customer import (
    CustomerCreate,
    CustomerRead,
    CustomerStageUpdate,
    CustomerUpdate,
    StageHistoryRead,
)
from app.schemas.document import CustomerDocumentRead
from app.schemas.kedl import (
    KedlDashboardMetrics,
    KedlDemandCreate,
    KedlDemandRead,
    KedlDemandUpdate,
    KedlDocumentRead,
    KedlFileInitRequest,
    KedlFileRead,
    KedlFileStatusUpdate,
    KedlFileUpdate,
    KedlStatusLogRead,
)
from app.schemas.lead import (
    LeadAssign,
    LeadConvert,
    LeadCreate,
    LeadMarkLost,
    LeadRead,
    LeadUpdate,
)
from app.schemas.payment import (
    CustomerPaymentsListResponse,
    PaymentAuditLogRead,
    PaymentCreate,
    PaymentRead,
    PaymentRejectRequest,
    PaymentSummary,
    PaymentUpdate,
)
from app.schemas.team import TeamCreate, TeamRead, TeamUpdate
from app.schemas.ticket import (
    TicketAssign,
    TicketCommentCreate,
    TicketCommentRead,
    TicketCreate,
    TicketImageRead,
    TicketRead,
    TicketStatusLogRead,
    TicketStatusUpdate,
)
from app.schemas.user import UserCreate, UserRead, UserUpdate
from app.schemas.work_assignment import (
    CalendarScheduleItem,
    CalendarScheduleResponse,
    CustomerShortForLabour,
    WorkAssignmentCreate,
    WorkAssignmentRead,
    WorkAssignmentUpdate,
    WorkPhotoRead,
    WorkStatusLogRead,
)

__all__ = [
    "ErrorDetail",
    "ErrorResponse",
    "HealthResponse",
    "PaginationParams",
    "PaginatedResponse",
    "OtpRequest",
    "OtpRequestResponse",
    "OtpVerify",
    "TokenResponse",
    "RefreshTokenRequest",
    "LogoutRequest",
    "FcmTokenUpdate",
    "UserMeResponse",
    "TeamCreate",
    "TeamUpdate",
    "TeamRead",
    "UserCreate",
    "UserUpdate",
    "UserRead",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerStageUpdate",
    "CustomerRead",
    "StageHistoryRead",
    "CustomerDocumentRead",
    "LeadCreate",
    "LeadUpdate",
    "LeadAssign",
    "LeadMarkLost",
    "LeadConvert",
    "LeadRead",
    "PaymentCreate",
    "PaymentUpdate",
    "PaymentRead",
    "PaymentRejectRequest",
    "PaymentSummary",
    "CustomerPaymentsListResponse",
    "PaymentAuditLogRead",
    "WorkAssignmentCreate",
    "WorkAssignmentUpdate",
    "WorkAssignmentRead",
    "WorkPhotoRead",
    "WorkStatusLogRead",
    "CustomerShortForLabour",
    "CalendarScheduleItem",
    "CalendarScheduleResponse",
    "KedlFileInitRequest",
    "KedlFileUpdate",
    "KedlFileStatusUpdate",
    "KedlDemandCreate",
    "KedlDemandUpdate",
    "KedlDemandRead",
    "KedlDocumentRead",
    "KedlStatusLogRead",
    "KedlFileRead",
    "KedlDashboardMetrics",
    "TicketCreate",
    "TicketCommentCreate",
    "TicketStatusUpdate",
    "TicketAssign",
    "TicketRead",
    "TicketImageRead",
    "TicketCommentRead",
    "TicketStatusLogRead",
    "TimelineStageItem",
    "ResponsibleContact",
    "ClientHomeResponse",
]
